# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-09 13:34:39
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Dissolve2023(input_2="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS_FULL_RI_2023", Value):  # Dissolve2023

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: If Field Exists (If Field Exists) ()
    True_31, False_30 = #  NOT  IMPLEMENTED(in_table=input_2.__str__().format(**locals(),**globals())if isinstance(input_2, str) else input_2, field_test_type="MUST_HAVE_ALL_FIELDS", field=["Field6", "Field8"])

    # Process: Make Feature Layer (3) (Make Feature Layer) (management)
    HPMS2023_Major = "HPMS2023_Major"
    if False_30:
        arcpy.management.MakeFeatureLayer(in_features=input_2.__str__().format(**locals(),**globals())if isinstance(input_2, str) else input_2, out_layer=HPMS2023_Major, where_clause="F_SYSTEM IN ('1', '2', '3') Or (F_SYSTEM = '4' And URBAN_ID <> '99999')")

    # Process: Calculate Field (Calculate Field) (management)
    if False_30:
        test = arcpy.management.CalculateField(in_table=HPMS2023_Major, field="AADT_NUM", expression="!AADT!", field_type="LONG")[0]

    # Process: Make Feature Layer (2) (Make Feature Layer) (management)
    HPMS2023_Major_State = "HPMS2023_Major_State"
    if False_30:
        arcpy.management.MakeFeatureLayer(in_features=test, out_layer=HPMS2023_Major_State, where_clause="AADT_NUM > 0 And Shape_Length > 0")

    # Process: Calculate Field (2) (Calculate Field) (management)
    if False_30:
        calculated = arcpy.management.CalculateField(in_table=HPMS2023_Major_State, field="REPEAT_TEST", expression="!RouteID!+!AADT!")[0]

    # Process: Calculate Field (5) (Calculate Field) (management)
    if False_30:
        HPMS2023_Major_State_2_ = arcpy.management.CalculateField(in_table=calculated, field="f_system", expression="!F_SYSTEM!", field_type="SHORT")[0]

    # Process: Calculate Field (3) (Calculate Field) (management)
    if False_30:
        HPMS2023_Major_State_3_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_State_2_, field="urban_code", expression="!URBAN_ID!", field_type="LONG")[0]

    # Process: Pairwise Dissolve (Pairwise Dissolve) (analysis)
    HPMS2023_Major_RI_7_ = "C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI"
    if False_30:
        arcpy.analysis.PairwiseDissolve(in_features=HPMS2023_Major_State_3_, out_feature_class=HPMS2023_Major_RI_7_, dissolve_field=["REPEAT_TEST"], statistics_fields=[["StateID", "FIRST"], ["urban_code", "FIRST"], ["AADT_NUM", "MEAN"], ["F_SYSTEM", "FIRST"]], multi_part="SINGLE_PART")

    # Process: Calculate Field (4) (Calculate Field) (management)
    if False_30:
        HPMS2023_Major_RI_5_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI_7_, field="ID", expression="!OBJECTID!", field_type="LONG")[0]

    # Process: Export Features (Export Features) (conversion)
    HPMS2023_Value_forJSON = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\EJSCREEN pipeline.gdb\HPMS2023_{Value}_forJSON"
    if False_30:
        arcpy.conversion.ExportFeatures(in_features=HPMS2023_Major_RI_5_, out_features=HPMS2023_Value_forJSON, field_mapping="state_code \"state_code\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_StateID,-1,-1;urban_code \"urban_code\" true true false 0 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_urban_code,-1,-1;f_system \"f_system\" true true false 255 Text 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_f_system,0,254;aadt \"aadt\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,MEAN_AADT_NUM,-1,-1;ID \"ID\" true true false 0 Long 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,ID,-1,-1")

    # Process: Features To JSON (Features To JSON) (conversion)
    HPMS2023_Value_json = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\HPMS2023_{Value}.json"
    if False_30:
        arcpy.conversion.FeaturesToJSON(in_features=HPMS2023_Value_forJSON, out_json_file=HPMS2023_Value_json, format_json="NOT_FORMATTED", geoJSON="NO_GEOJSON", outputToWGS84="KEEP_INPUT_SR", use_field_alias="USE_FIELD_NAME")

    # Process: Make Feature Layer (4) (Make Feature Layer) (management)
    HPMS2023_Major_X = "HPMS2023_Major_X"
    if True_31:
        arcpy.management.MakeFeatureLayer(in_features=input_2.__str__().format(**locals(),**globals())if isinstance(input_2, str) else input_2, out_layer=HPMS2023_Major_X, where_clause="Field6 IN ('1', '2', '3') Or (Field6 = '4' And Field8 <> '99999')")

    # Process: Calculate Field (6) (Calculate Field) (management)
    if True_31:
        HPMS2023_Major_RI_3_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_X, field="AADT_NUM", expression="!AADT!", field_type="LONG")[0]

    # Process: Make Feature Layer (5) (Make Feature Layer) (management)
    HPMS2023_Major_RI_4_ = "HPMS2023_Major_RI"
    if True_31:
        arcpy.management.MakeFeatureLayer(in_features=HPMS2023_Major_RI_3_, out_layer=HPMS2023_Major_RI_4_, where_clause="AADT_NUM > 0 And Shape_Length > 0")

    # Process: Calculate Field (7) (Calculate Field) (management)
    if True_31:
        HPMS2023_Major_RI_2_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI_4_, field="REPEAT_TEST", expression="!RouteID!+!AADT!")[0]

    # Process: Calculate Field (8) (Calculate Field) (management)
    if True_31:
        HPMS2023_Major_RI_6_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI_2_, field="f_system", expression="!Field6!", field_type="SHORT")[0]

    # Process: Calculate Field (9) (Calculate Field) (management)
    if True_31:
        HPMS2023_Major_RI_10_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI_6_, field="urban_code", expression="!Field8!", field_type="LONG")[0]

    # Process: Pairwise Dissolve (2) (Pairwise Dissolve) (analysis)
    HPMS2023_Major_RI_11_ = "C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI"
    if True_31:
        arcpy.analysis.PairwiseDissolve(in_features=HPMS2023_Major_RI_10_, out_feature_class=HPMS2023_Major_RI_11_, dissolve_field=["REPEAT_TEST"], statistics_fields=[["StateID", "FIRST"], ["urban_code", "FIRST"], ["AADT_NUM", "MEAN"], ["f_system", "FIRST"]], multi_part="SINGLE_PART")

    # Process: Calculate Field (10) (Calculate Field) (management)
    if True_31:
        HPMS2023_Major_RI_12_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI_11_, field="ID", expression="!OBJECTID!", field_type="LONG")[0]

    # Process: Export Features (2) (Export Features) (conversion)
    HPMS2023_Value_forJSON_2_ = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\EJSCREEN pipeline.gdb\HPMS2023_{Value}_forJSON"
    if True_31:
        arcpy.conversion.ExportFeatures(in_features=HPMS2023_Major_RI_12_, out_features=HPMS2023_Value_forJSON_2_, field_mapping="state_code \"state_code\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_StateID,-1,-1;urban_code \"urban_code\" true true false 0 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_urban_code,-1,-1;f_system \"f_system\" true true false 255 Text 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_f_system,0,254;aadt \"aadt\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,MEAN_AADT_NUM,-1,-1;ID \"ID\" true true false 0 Long 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,ID,-1,-1")

    # Process: Features To JSON (2) (Features To JSON) (conversion)
    HPMS2023_Value_json_2_ = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\HPMS2023_{Value}.json"
    if True_31:
        arcpy.conversion.FeaturesToJSON(in_features=HPMS2023_Value_forJSON_2_, out_json_file=HPMS2023_Value_json_2_, format_json="NOT_FORMATTED", geoJSON="NO_GEOJSON", outputToWGS84="KEEP_INPUT_SR", use_field_alias="USE_FIELD_NAME")

    # Process: Delete (Delete) (management)
    if False_30 and True_31:
        Delete_Succeeded = arcpy.management.Delete(in_data=[HPMS2023_Major_RI_12_, HPMS2023_Major_RI_5_])[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb", workspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb"):
        Dissolve2023(*argv[1:])
