# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-09 13:33:36
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Dissolve2020(this_input="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS_FULL_RI_2023", Value="Value"):  # Dissolve2020

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Make Feature Layer (Make Feature Layer) (management)
    HPMS_FULL_RI_2023_Layer = "HPMS_FULL_RI_2023_Layer"
    arcpy.management.MakeFeatureLayer(in_features=this_input.__str__().format(**locals(),**globals())if isinstance(this_input, str) else this_input, out_layer=HPMS_FULL_RI_2023_Layer, where_clause="F_SYSTEM IN (1, 2, 3) Or (F_SYSTEM = 4 And URBAN_CODE <> 99999)")

    # Process: Make Feature Layer (2) (Make Feature Layer) (management)
    HPMS_FULL_RI_2023_Layer_2_ = "HPMS_FULL_RI_2023_Layer1"
    arcpy.management.MakeFeatureLayer(in_features=HPMS_FULL_RI_2023_Layer, out_layer=HPMS_FULL_RI_2023_Layer_2_, where_clause="AADT > 0 And Shape_Length > 0")

    # Process: Calculate Field (12) (Calculate Field) (management)
    calculated_2_ = arcpy.management.CalculateField(in_table=HPMS_FULL_RI_2023_Layer_2_, field="REPEAT_TEST", expression="repeat(!Route_ID!,!AADT!)", code_block="""def repeat(r,a):
    r = str(r)
    a = str(a)
    return r+a""")[0]

    # Process: Pairwise Dissolve (3) (Pairwise Dissolve) (analysis)
    HPMS2023_Major_RI = "C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI"
    arcpy.analysis.PairwiseDissolve(in_features=calculated_2_, out_feature_class=HPMS2023_Major_RI, dissolve_field=["REPEAT_TEST"], statistics_fields=[["State_Code", "FIRST"], ["URBAN_CODE", "FIRST"], ["AADT", "MEAN"], ["F_SYSTEM", "FIRST"]], multi_part="SINGLE_PART")

    # Process: Calculate Field (15) (Calculate Field) (management)
    HPMS2023_Major_RI_9_ = arcpy.management.CalculateField(in_table=HPMS2023_Major_RI, field="ID", expression="!OBJECTID!", field_type="LONG")[0]

    # Process: Export Features (3) (Export Features) (conversion)
    HPMS2020_Value_forJSON = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\EJSCREEN pipeline.gdb\HPMS2020_{Value}_forJSON"
    if Value:
        arcpy.conversion.ExportFeatures(in_features=HPMS2023_Major_RI_9_, out_features=HPMS2020_Value_forJSON, field_mapping="state_code \"state_code\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_State_Code,-1,-1;urban_code \"urban_code\" true true false 0 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_URBAN_CODE,-1,-1;f_system \"f_system\" true true false 255 Text 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,FIRST_F_SYSTEM,0,254;aadt \"aadt\" true true false 4 Double 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,MEAN_AADT,-1,-1;ID \"ID\" true true false 0 Long 0 0,First,#,C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb\\HPMS2023_Major_RI,ID,-1,-1")

    # Process: Features To JSON (3) (Features To JSON) (conversion)
    HPMS2020_Value_json = fr"C:\Users\enost\Documents\ArcGIS\Projects\EJSCREEN pipeline\HPMS2020_{Value}.json"
    if Value:
        arcpy.conversion.FeaturesToJSON(in_features=HPMS2020_Value_forJSON, out_json_file=HPMS2020_Value_json, format_json="NOT_FORMATTED", geoJSON="NO_GEOJSON", outputToWGS84="KEEP_INPUT_SR", use_field_alias="USE_FIELD_NAME")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb", workspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb"):
        Dissolve2020(*argv[1:])
