# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-09 13:32:46
"""
import arcpy
import os

from EJSCREENpipelineatbx.Dissolve2020 import Dissolve2020
def FeatureClassGenerator(workspace, wild_card, feature_type, recursive) :
  with arcpy.EnvManager(workspace = workspace):

    dataset_list = [""]
    if recursive:
      datasets = arcpy.ListDatasets()
      dataset_list.extend(datasets)

    for dataset in dataset_list:
      featureclasses = arcpy.ListFeatureClasses(wild_card, feature_type, dataset)
      for fc in featureclasses:
        yield os.path.join(workspace, dataset, fc), fc


def Prep2020():  # Prep2020

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    EJSCREEN_pipeline_gdb = "C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb"

    for data, Name in FeatureClassGenerator(EJSCREEN_pipeline_gdb, "*_2020", "", "NOT_RECURSIVE"):

        # Process: Get_Field_Value (Get Field Value) 
        # Get Field Value Utility is not implemented 

        # Process: Dissolve2020 (Dissolve2020) (EJSCREENpipelineatbx)
        Dissolve2020(this_input=data, Value=Value)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb", workspace="C:\\Users\\enost\\Documents\\ArcGIS\\Projects\\EJSCREEN pipeline\\EJSCREEN pipeline.gdb"):
        Prep2020()
